### ISSUE TITLE
Overhead from SecureRandom in Buddy benchmarks

### ISSUE THREAD

**Issue by tonivanhala** [gerritjvv/crypto#1]
Buddy benchmarks use `buddy.core.nonce/random-bytes`, which [creates a new `SecureRandom` instance on each invokation](https://github.com/funcool/buddy-core/blob/58ee19e3ee0c40e82740d670bc66bd8bd54da2ea/src/buddy/core/nonce.clj#L27-L37). This may introduce significant overhead, as the instantiation of `SecureRandom` is a blocking operation that depends on available entropy. 

**Impact**: The overhead in Buddy benchmarks hinders comparing their metrics to other benchmarks, as they do not contain similar overhead, but [reuse the `SecureRandom` instance](https://github.com/gerritjvv/crypto/blob/5f5fc1f62885823ba448ff0d396a80510aa26b9d/crypto-core/src/main/java/crypto/Random.java#L7). 

**Potential solution**: invoke the `buddy.core.nonce/random-bytes` two arg version, which uses the SecureRandom instance provided as the second parameter.

**Comment by gerritjvv** [comment]
Hi thanks for finding this.
I did a quick update as you suggested, the through put doubled but its still only ~+500 op/s , way less than the thousands per second that the other libs and even the just bouncy castle shows.

I'll run a full benchmark and re-publish the results.

**Comment by gerritjvv** [comment]
see https://github.com/gerritjvv/crypto/pull/2/files (ignore the html part which crept in from the blog post preps :) ).

**Comment by tonivanhala** [comment]
Thanks for the quick fix! Now I feel much more confident in using these benchmarks as a reference.
:+1:

**Comment by gerritjvv** [comment]
https://github.com/gerritjvv/crypto/tree/master/crypto-perf this page now contains the new changes made and another set of aes vs non aes benchmarks.
