### ISSUE TITLE
Tag and release

### ISSUE THREAD

**Issue by simmel** [gerritjvv/crypto#5]
Please create a new tag and do a new release from that tag.

The [maven-release-plugin](https://maven.apache.org/maven-release/maven-release-plugin/) is perfect for handling releases together with [mavent-gpg-plugin](https://maven.apache.org/plugins/maven-gpg-plugin/) with the `useAgent` setting.

Thanks shaping up the Java crypto space = )

**Comment by gerritjvv** [comment]
thanks. I'll try this out on the next release.
